baseURL = 'https://kamyabnazari.org/'
languageCode = 'en-us'
title = 'Kamyab Nazari'
theme = "PaperMod"

[params]
env = "production"
title = "Kamyab Nazari"
description = "Personal Portfolio website for my projects and cv."
keywords = ["Blog", "Portfolio"]
author = "Kamyab Nazari"
dataFormat = "January 2, 2006"
defaultTheme = "auto"
showBreadCrumbs = true
showPostNavLinks = true
showCodeCopyButtons = true
comments = false

[params.label]
icon = "favicons/favicon-header.png"
iconHeight = 48

[params.profileMode]
enabled = true
title = "Kamyab Nazari"
subtitle = "Everyone has a responsibility to reach one’s true potential."
imageUrl = "/profile-avatar.jpeg"
imageTitle = "Avatar"
imageWidth = 240
imageHeight = 240

[[params.profileMode.buttons]]
name = "About Me"
url = "about-me"

[[params.profileMode.buttons]]
name = "Projects"
url = "/projects"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/kamyabnazari"

[[params.socialIcons]]
name = "Github"
url = "https://github.com/kamyabnazari"

[params.assets]
favicon = "favicons/favicon.ico"
favicon16x16 = "favicons/favicon-16x16.png"
favicon32x32 = "favicons/favicon-32x32.png"
apple_touch_icon = "favicons/apple-touch-icon.png"
safari_pinned_tab = "favicons/safari-pinned-tab.svg"

# Menu

[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact"
weight = 30